# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

from result_contract_io import run_question_scaffold


QUESTION = {
  "question_id": "Q2",
  "title": "问题二",
  "task_type": "分类/识别",
  "core_goal": "已知两种零配件和成品次品率，请为企业生产过程的各个阶段作出决策：",
  "baseline_model": "逻辑回归、朴素贝叶斯或决策树",
  "main_model": "随机森林、梯度提升或代价敏感学习",
  "backup_models": [
    "逻辑回归",
    "随机森林",
    "梯度提升树"
  ],
  "model_reason": "该问属于“分类/识别”任务，随机森林、梯度提升或代价敏感学习 能在保留可解释性的同时承接题目约束：请根据你们所做的决策， 对表 1 中的情形给出具体的决策方案，并给出决策的依据及相。",
  "formula_requirements": [
    "定义特征与类别标签",
    "说明分类函数或判别规则",
    "给出 Precision/Recall/F1 等指标"
  ],
  "validation": [
    "混淆矩阵",
    "Precision/Recall/F1",
    "ROC/AUC 或 PR 曲线"
  ],
  "figures": [
    {
      "figure_id": "fig_q2_1",
      "title": "混淆矩阵热力图",
      "purpose": "支撑Q2的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q2_1.png"
    },
    {
      "figure_id": "fig_q2_2",
      "title": "ROC 曲线",
      "purpose": "支撑Q2的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q2_2.png"
    },
    {
      "figure_id": "fig_q2_3",
      "title": "特征重要性图",
      "purpose": "支撑Q2的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q2_3.png"
    }
  ],
  "paper_sections": [
    "问题二模型建立",
    "问题二结果分析",
    "问题二模型检验"
  ]
}


if __name__ == "__main__":
    raise SystemExit(run_question_scaffold(QUESTION))
