# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

from result_contract_io import run_question_scaffold


QUESTION = {
  "question_id": "Q4",
  "title": "问题四",
  "task_type": "优化/规划",
  "core_goal": "假设问题 2 和问题 3 中零配件、 半成品和成品的次品率均是通过抽样检测方法",
  "baseline_model": "线性规划、整数规划或可行规则基线",
  "main_model": "多目标规划、启发式算法、遗传算法或模拟退火",
  "backup_models": [
    "整数规划",
    "遗传算法",
    "模拟退火"
  ],
  "model_reason": "该问属于“优化/规划”任务，多目标规划、启发式算法、遗传算法或模拟退火 能在保留可解释性的同时承接题目约束：某企业生产某种畅销的电子产品，需要分别购买两种零配件（零配件 1 和零配件 2），。",
  "formula_requirements": [
    "定义决策变量",
    "写清目标函数",
    "列出约束条件与可行域"
  ],
  "validation": [
    "可行性检查",
    "约束满足率",
    "与基准策略对比",
    "敏感性分析"
  ],
  "figures": [
    {
      "figure_id": "fig_q4_1",
      "title": "方案对比柱状图",
      "purpose": "支撑Q4的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q4_1.png"
    },
    {
      "figure_id": "fig_q4_2",
      "title": "约束满足情况图",
      "purpose": "支撑Q4的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q4_2.png"
    },
    {
      "figure_id": "fig_q4_3",
      "title": "敏感性分析折线图",
      "purpose": "支撑Q4的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q4_3.png"
    }
  ],
  "paper_sections": [
    "问题四模型建立",
    "问题四结果分析",
    "问题四模型检验"
  ]
}


if __name__ == "__main__":
    raise SystemExit(run_question_scaffold(QUESTION))
