# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

import subprocess
import sys
from pathlib import Path


THIS_DIR = Path(__file__).resolve().parent


def main() -> int:
    scripts = sorted(path for path in THIS_DIR.glob("q*_model.py") if path.name[:1].lower() == "q")
    if not scripts:
        print("No q*_model.py scripts found.")
        return 0
    failures = 0
    for script in scripts:
        print(f"=== Running {script.name} ===")
        result = subprocess.run([sys.executable, str(script)], cwd=str(THIS_DIR), check=False)
        if result.returncode != 0:
            failures += 1
            print(f"[warning] {script.name} exited with code {result.returncode}")
    if failures:
        print(f"Completed with {failures} failed modeling script(s).")
        return 1
    print("All modeling scaffold scripts completed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
