from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path


BASE_DIR = Path.cwd().resolve()
OUTPUT_DIR = BASE_DIR / "paper_output"


def configure_utf8_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except Exception:
            pass


DIRECTORIES = [
    "step1",
    "plan",
    "code/data_processing",
    "code/visualization",
    "code/modeling",
    "code/qa",
    "data_cleaned",
    "figures",
    "tables",
    "results",
    "micro_units",
]


OUTPUT_LAYOUT = """# MathModel Skill Output Layout

This file is generated by `paper-workflow-orchestrator/scripts/prepare_output_layout.py`.

All paths are relative to the project root. The skill package directory is a reusable tool area; current-contest generated files should stay under `paper_output/`.

## Input

```text
problem_files/      # contest problem PDF/Word and official attachments
crawled_data/       # optional external public data
```

## Generated Code

```text
paper_output/code/
├── data_processing/   # current-contest data cleaning scripts generated or modified by Agent
├── visualization/     # current-contest figure/table plotting scripts generated or modified by Agent
├── modeling/          # q1_model.py, q2_model.py, q3_model.py, run_modeling.py, result_contract_io.py
└── qa/                # optional current-contest validation/check scripts
```

Do not write current-contest generated code back into installed skill package directories. Those folders are reusable code templates.

## Contracts And Evidence

```text
paper_output/step1/                 # problem analysis
paper_output/plan/                  # model route, scoring, data and visualization plans
paper_output/results/               # model_results.json, metrics.json, conclusions.json
paper_output/tables/                # table_index.json and paper-ready CSV tables
paper_output/figure_index.json      # figure evidence index
```

## Data, Figures, And Text

```text
paper_output/data_cleaned/          # cleaned CSV/XLSX exports
paper_output/figures/               # paper-ready images; EDA figures may use subfolders
paper_output/tasks.json             # micro-unit task manifest
paper_output/micro_units/           # generated micro-unit text files
paper_output/final_paper.md         # merged Markdown draft
paper_output/final_paper.docx       # Word draft
paper_output/ref_check.md           # reference and evidence check report
```

Generated code should write real results back to `paper_output/results/` and `paper_output/tables/`, then QA should regenerate or verify `paper_output/tasks.json` before final text generation.
"""


CODE_README = """# Current Contest Code Workspace

This directory is for code generated or modified for the current contest problem.

The skill package `scripts/` directories are reusable templates and code-level prompts. Do not write contest-specific scripts back into installed skill package directories.

## Subdirectories

```text
paper_output/code/
├── data_processing/   # cleaning, feature engineering, field mapping, dataset joins
├── visualization/     # paper-ready plotting scripts and figure/table formatting scripts
├── modeling/          # q1/q2/q3 modeling scripts and result contract writers
└── qa/                # optional contest-specific validation/check scripts
```

Generated code should read from `problem_files/`, `crawled_data/`, `paper_output/plan/`, and `paper_output/data_cleaned/`, then write outputs back to `paper_output/data_cleaned/`, `paper_output/figures/`, `paper_output/tables/`, and `paper_output/results/`.
"""


SUBDIR_READMES = {
    "code/data_processing/README.md": """# Data Processing Code

Put current-contest cleaning and feature engineering scripts here.

Expected outputs:

- `paper_output/data_cleaned/*_cleaned.csv`
- updated data notes or field mapping artifacts when needed

Do not edit reusable skill package scripts directly for one contest dataset.
""",
    "code/visualization/README.md": """# Visualization Code

Put current-contest plotting and formatted chart/table rendering scripts here.

Expected outputs:

- `paper_output/figures/fig_q*_*.png`
- `paper_output/figure_index.json`
- optional table formatting helpers that write to `paper_output/tables/`

Use skill package scripts as style templates, then adapt the code to the current data fields and model outputs.
""",
    "code/modeling/README.md": """# Modeling Code

Put current-contest modeling scripts here.

Recommended files:

- `run_modeling.py`
- `result_contract_io.py`
- `q1_model.py`
- `q2_model.py`
- `q3_model.py`

Expected outputs:

- `paper_output/results/model_results.json`
- `paper_output/results/metrics.json`
- `paper_output/results/conclusions.json`
- `paper_output/tables/table_index.json`
- `paper_output/tables/*.csv`

`model-code-and-result-generator` may overwrite this README with a question-specific workspace note after reading `model_route.json`.
""",
    "code/qa/README.md": """# QA Code

Put optional current-contest validation scripts here.

Examples:

- check whether table paths in `table_index.json` exist
- check whether figures referenced by the paper exist
- check whether model result contracts still contain draft placeholders

General workflow QA remains in the reusable `quality-assurance-auditor` skill.
""",
}


def main() -> int:
    configure_utf8_stdio()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for dirname in DIRECTORIES:
        (OUTPUT_DIR / dirname).mkdir(parents=True, exist_ok=True)

    content = OUTPUT_LAYOUT.rstrip() + "\n\n"
    content += f"Generated at: {datetime.now().isoformat(timespec='seconds')}\n"
    (OUTPUT_DIR / "OUTPUT_LAYOUT.md").write_text(content, encoding="utf-8")
    (OUTPUT_DIR / "code" / "README.md").write_text(CODE_README.rstrip() + "\n", encoding="utf-8")
    for relative_path, readme in SUBDIR_READMES.items():
        target = OUTPUT_DIR / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            target.write_text(readme.rstrip() + "\n", encoding="utf-8")
    print(f"✅ 已准备输出目录规划：{OUTPUT_DIR / 'OUTPUT_LAYOUT.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
